name: Hello World!

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Get date
        run: |
          date
  directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Get directory
        run: |
          ls -l